### ISSUE TITLE
crash on spider

### ISSUE THREAD

**Issue by tomchambers2** [random-quark/emotional-mirror-backend#1]
```
Traceback (most recent call last):
  File "twitterEmoSpider.py", line 90, in <module>
    stream.filter(track=config.words_to_track)
  File "/Users/tomchambers/projects/emotional-mirror-backend/twitterEmoSpider/venv/lib/python2.7/site-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/Users/tomchambers/projects/emotional-mirror-backend/twitterEmoSpider/venv/lib/python2.7/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/Users/tomchambers/projects/emotional-mirror-backend/twitterEmoSpider/venv/lib/python2.7/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
KeyError: 'retweeted'
(venv)~/projects/emotional-mirror-backend/twitterEmoSpider > 
```

**Comment by lobodelmar** [comment]
yes, this is the error that I could not solve yesterday @ 4pm. If you take
our the retweeted line it complains on the next. I'll fix it later today.
It just means you have to restart the spider every so often. But it's
enough to load enough data on the db.
tp
